### ISSUE TITLE
Pull out wordpiece_encode?

### ISSUE THREAD

**Issue by jonthegeek** [bnosac/sentencepiece#7]
`wordpiece_encode` is a *little* out of place, since it's not really the same as `sentencepiece`. I'm probably going to wrap it into its own package, since it's all we need for the moment. Would you want to cut it out of sentencepiece, or maybe import the smaller package?

I appreciate the help in any case!

**Comment by jwijffels** [comment]
When creating wordpiece_encode, I thought that putting that simple function in a separate R package would be too much. Either I would have put it in R package sentencepiece or R package tokenizers.bpe. I chose sentencepiece because it follows similar logic.

If you only need the wordpiece_encode functionality. You are free to create a new package or put the code in your own package as it is open source. Just make sure you abide by the license (https://github.com/bnosac/sentencepiece/blob/master/LICENSE and https://github.com/bnosac/sentencepiece/blob/master/LICENSE.note) like you would do with any other software.

I have no plans to let R package sentencepiece depend on another package, it only Import Rcpp currently, I prefer to have packages with no or at least as possible dependencies for reasons of maintenance.

**Comment by jonthegeek** [comment]
Ok, will do! I'm not super familiar with MPL, but I'll be careful to follow it!

**Comment by jwijffels** [comment]
MPL is in short is a copyleft license allowing as well to incorporate it into commercial products without disclosing the other source code where it is incorporated in.

**Comment by jonthegeek** [comment]
As discussed elsewhere, we ended up just extracting (and cleaning up) the code we already had in jonathanbratt/RBERT. We preferred the {stringr} dependency to C++ code we'd have to maintain ourselves. After I did the speed test to confirm they were similar, @jonathanbratt never even looked at the {sentencepiece} version to ensure that he wasn't copying anything. The two approaches ended up being very different.
